import ohhkay from '../assets/covers/iphi.jpeg';
import tseleng from "../assets/covers/Tseleng.jpg";
import brakop from "../assets/covers/Bra Kop Cover.jpeg"
import mothokesera from  "../assets/covers/motho ke sera.jpeg"
import lepara from "../assets/covers/Lepara - Cover.jpeg"
import kaorata from "../assets/covers/Kao Rata.jpg"
import shadow from "../assets/covers/shadow.jpg"
import jawbreaker from "../assets/covers/jawbreaker.jpeg"
import nobodySafe from "../assets/covers/not-safe.jpg"
import money from "../assets/covers/Money - Cover.jpg"
import chacha from "../assets/covers/Cha Cha.jpg"
import sparne from "../assets/covers/Sparne.jpg"
import unstoppable from "../assets/covers/Unstoppable.png"
import sobbing from "../assets/covers/Sobbing Cover.jpeg"
import topseven from  "../assets/covers/Top  Seven - Cover.jpeg"
import marijuana from "../assets/covers/Marijuana.jpeg"
import success from "../assets/covers/Success - Cover.jpg"
import ptl from "../assets/covers/Praise The Lord - Cover.jpeg"
import respect from "../assets/covers/respect.jpeg"
import maleboo from "../assets/covers/maleboo.jpg"

export const singles = [
    {
        id:1,
        name: "Sonwabile",
        single: "Ohhkay", 
        type: "Single",
        composer: "Sonwabile Dyanose & Maphutha Aggrey",
        image:  ohhkay,
        description: `Ohhkay is a song by a South African YouTuber and artist Sonwabile, featured on his EP, "IPHI", which officially debuted on Nov 29, 2024.`,
        date: "November 29 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://www.youtube.com/watch?v=hdfQCyUVvMk",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/2gGnJC1CEiPBBlGDbBooOO",
    },

    {
        id:2,
        name: "Brocklyna",
        single: "Tseleng",
        type: "Single",
        composer: "Temosho & Maphutha Aggrey",
        image: tseleng,
        description: `An Afro Pop by Brocklyna from Limpopo. The song was featured on Limpopo Podcast.`,
        date: "July 31 2024",
        genre: "Afro Pop",
        youtubeUrl: "https://www.youtube.com/watch?v=XydYkZ6f0oc",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/15DOAdJWd1tsk8lLi6sg1W/",
    },

    {
        id:3,
        name: "Kraws Bohnz",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        single: "Bra Kop",
        image: brakop,
        type: "Single",
        description: `Bra Kop' by Kraws Bohnz, a standout track from 1060.`,
        date: "May 12 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/-ILDDEbr7o4?si=-ikXcBvoNPF1VSV7",
        geniuxUrl: "https://music.geniux.co.za/playing/26683031019",
    },

    {
        id:4,
        name: "Frank Gomez",
        single: "Motho Ke Sera",
        composer: "Nkateko Theodore Maranela & Maphutha Aggrey",
        image: mothokesera,
        type: "Single",
        description: `MOTHO KE SERA. Produced by Veteran Beatx.`,
        date: "August 16 2024",
        genre: "Rap/Hip Hop",
        youtubeUrl: "https://youtu.be/C-GADo9AF5Q?si=dv2cRZdNDaVGcfNZ",
        geniuxUrl: "https://music.geniux.co.za/playing/40145037399",
    },
    {
        id:5,
        name: "Freeze Linet",
        composer: "Rodger Maphutha, Thapelo Maphutha & Maphutha Aggrey",
        single: "Lepara",
        image: lepara,
        type: "Single",
        description: `A Hit by Freeze Linett, Produced by Thapelo, and engineered by Veteran Beatx`,
        date: "July 24 2020",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://www.youtube.com/watch?v=Bh7C9n4QEEU",
        geniuxUrl: "https://music.geniux.co.za/playing/7257058929",
    },

    {
        id:6,
        name: "Keah",
        single: "Kao Rata (Ft. Recky R)",
        composer: "Kea & Maphutha Aggrey",
        description: `An Amapiano/Deep House jam, Engineered by Veteran Beatx which features Keah & Recky R`,
        image: kaorata,
        type: "Single",
        date: "November 5 2022",
        genre: "Amapiano",
        youtubeUrl: "https://youtu.be/xa0OiXmXC4M?si=9ZtNsBM-5RyC_kBP",
        geniuxUrl: "https://music.geniux.co.za/playing/88995415106",
    },
    {
        id:7,
        name: "Wasavii",
        composer: "Kgaogelo Rapolae & Maphutha Aggrey, Maphutha Evidence",
        single: "Shadow",
        description: `A classic rap by Wasavii, featured in his long-awaited, upcoming EP "W.A.N.T.S".`,
        image: shadow,
        type: "Single",
        date: "July 24 2021",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/4545615218",
    },
    {
        id:8,
        name: "Sbuu",
        single: "Jawbreaker",
        composer: "Sibusiso Sijeku & Maphutha Aggrey",
        description: `Banger from Sonwabile's videographer 'Sbuu', featured on his project 'All In One EP' Produced By Veteran Beatx & Lucent.exe`,
        image: jawbreaker,
        type: "Single",
        date: "September 19 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/BRDTDkoo2cw?si=6vMhj8B6dgXhubTA",
        geniuxUrl: "https://music.geniux.co.za/playing/35288251013",
    },

    {
        id:9,
        name: "Savage X",
        single: "Nobody Safe",
        composer: "Seun & Maphutha Aggrey",
        description: `Nobody Safe, a single track by Savage X (SVG X), Engineered By Veteran Beatx`,
        image: nobodySafe,
        type: "Single",
        date: "April 19 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/1534510691",
    },

    {
        id:10,
        name: "Corey",
        single: "Money",
        composer: "Ronald Tladi & Maphutha Aggrey",
        description: `Money, a single track by Corey, Produced By Veteran Beatx`,
        image: money,
        type: "Single",
        date: "November 11 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/65053451666",
    },
    {
        id:11,
        name: "Germtee",
        single: "Cha-Cha (Ft. SASS)",
        composer: "German, Tsebo & Maphutha Aggrey",
        description: `Cha Cha, featuring SASS, Re-Produced By Veteran Beatx, Released on: 2021-10-13`,
        image: chacha,
        type: "Single",
        date: "October 10 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/-5IpaO10nzU?si=N8-x6YOWH-kL8JfM",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/32V5kMPpQQgjaDGwmMutxj/",
    },
    {
        id:12,
        name: "Freeze Linett",
        single: "Sparne",
        composer: "Rodger Maphutha & Maphutha Aggrey",
        description: `Hard Trap song by Freeze Linett, Produced By Veteran Beatx`,
        image: sparne,
        type: "Single",
        date: "October 10 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/75676034544",
    },
    {
        id:13,
        name: "Milk Dope",
        single: "Unstoppable",
        composer: "Bruce Bapela & Maphutha Aggrey",
        description: `Unstoppable, featuring Issa Jay, Re-Produced By Veteran Beatx`,
        image: unstoppable,
        type: "Single",
        date: "August 6 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/7034753845/",
    },
    {
        id:14,
        name: "Kraws Bohnz",
        single: "Sobbing",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        description: `Kinda touching sad song by Kraws Bohnz, Produced By Veteran Beatx`,
        image: sobbing,
        type: "Single",
        date: "May 12 2023",
        genre: "Rap/Hip Hop",
        youtubeUrl: "https://youtu.be/HO8XVfF0n6o?si=D5AwQ0UroYNgdhq0",
        geniuxUrl: "https://music.geniux.co.za/playing/38795547441/",
    },
    {
        id:15,
        name: "Manila R",
        single: "Top 7",
        type: "Single",
        composer: "Tshepiso Manala & Maphutha Aggrey",
        description: `Veteran Beatx's first banger he produced, Dropped in 2017 by Manila R`,
        image: topseven,
        date: "December 10 2017",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "",
    },
    {
        id:16,
        name: "Rod",
        single: "Marijuana 2.0",
        composer: "Rodney Dolamo, Tshepiso Manala & Maphutha Aggrey",
        description: `Marijuana 2.0 featuring Chutney, Manila R, Kraws Bohnz, Razor McPablo, Savage X and Germtee`,
        image: marijuana,
        type: "Single",
        date: "April 20 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "",
    },
    {
        id:17,
        name: "Corey",
        single: "Success",
        composer: "Ronald Tladi & Maphutha Aggrey",
        description: `Success, a single track by Corey, Produced By Veteran Beatx`,
        image: success,
        type: "Single",
        date: "September 2 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/29948781798",
    },
    {
        id:18,
        name: "Kraws Bohnz",
        single: "Praise The Lord",
        composer: "Thabo Mashabela, Manala Phemelo, Evidence Maphutha & Maphutha Aggrey",
        image: ptl,
        type: "Single",
        description: `Praise The Lord' by Kraws Bohnz & Razor McPablo, Produced by Notorioux and engineered by Veteran Beatx.`,
        date: "August 4 2020",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/40145037399",
    },
    {
        id:19,
        name: "Kraws Bohnz",
        single: "Respect",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        image: respect,
        type: "Single",
        description: `Respect' by Kraws Bohnz, Dropped in 2020, Produced by Veteran Beatx.`,
        date: "May 22 2020",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/19104390562",
    },
    {
        id:20,
        name: "Maleboo",
        single: "Buti (Ft. Shibu Molomo)",
        composer: "Maleboo & Maphutha Aggrey",
        image: maleboo,
        type: "Single",
        description: `Buti (Ft. Shibu Molomo) Prod. Veteran Beatx featured in Maleboo's Album "Lesole Ntweng"`,
        date: "Mar 29 2025",
        genre: "Rap/Hip Hop",
        youtubeUrl: "https://youtu.be/tU9DaUAXW3I?si=HHOkxn4ZqENEzIwn",
        geniuxUrl: "",
    },
]
